#!/bin/sh
# postinst script for lvrt-schroot

# Check for the existence if liblinxdevice
# and add a symlink to the appropriate version
CHROOTPATH=/srv/chroot/labview

RPI2LINX=liblinxdevice_rpi2.so
RPI2LINXPATH=/usr/lib/$RPI2LINX
RPI5LINX=liblinxdevice_rpi5.so
RPI5LINXPATH=/usr/lib/$RPI5LINX

BBLINX=liblinxdevice_bbb.so
BBLINXPATH=/usr/lib/$BBLINX

USRBINPATH=/usr/bin
LINXPATH=$CHROOTPATH/usr/lib/liblinxdevice.so
PREAMBLE="<?xml version=\"1.0\" standalone='no'?>"
FMTSTR='<!DOCTYPE service-group SYSTEM "avahi-service.dtd">\n<service-group>\n  <name replace-wildcards="yes">%%h</name>\n  <service>\n    <type>_ni._tcp</type>\n    <port>3580</port>\n    <txt-record>ProdName=%s</txt-record>\n    <txt-record>DevClass=LINX</txt-record>\n  </service>\n</service-group>\n'
AVAHISVC=/etc/avahi/services/lvrt.service

# symlink update-ca-certificates to make ca-certificates pkg happy
ln -sf /usr/sbin/update-ca-certificates $CHROOTPATH/usr/bin/update-ca-certificates

# make sure resolv.conf exists; this will make schroot able to bind mount to it
rm -rf $CHROOTPATH/etc/resolv.conf 2>/dev/null
touch $CHROOTPATH/etc/resolv.conf

# make sure /etc/ssl/certs/ca-certificates.crt exists; this will make schroot able to bind mount to it
mkdir -p -m755 $CHROOTPATH/etc/ssl/certs
rm -rf $CHROOTPATH/etc/ssl/certs/ca-certificates.crt 2>/dev/null
touch $CHROOTPATH/etc/ssl/certs/ca-certificates.crt

if [ -e $CHROOTPATH$RPI2LINXPATH ]; then
	# Raspberry Pi 2,3,4, or 5
	# cat /proc/cpuinfo | grep BCM2709 > /dev/null && :
	# test -e /sys/firmware/devicetree/base/model && cat /sys/firmware/devicetree/base/model | 
	#    sed -e 's, Model.*,\n,' -e 's, Rev.*,\n,' | grep 'Raspberry Pi [234]' > /dev/null && :
	if [ -e /usr/bin/raspi-config ]; then
		# Detect the RPi hardware model
		MODEL=$(tr -d '\0' </sys/firmware/devicetree/base/model)

		# Create symlink to correct binaries
		case "$MODEL" in
			*"Raspberry Pi 5"*)
				ln -sf $RPI5LINX $LINXPATH
				chmod 0755 $LINXPATH
				test -x $CHROOTPATH/$USRBINPATH/linxtcpserver-rpi5 && ln -sf linxtcpserver-rpi5 $CHROOTPATH/$USRBINPATH/linxtcpserver
				test -x $CHROOTPATH/$USRBINPATH/linxserialserver-rpi5 && ln -sf linxserialserver-rpi5 $CHROOTPATH/$USRBINPATH/linxserialserver
				test -x $CHROOTPATH/$USRBINPATH/linxioserver-rpi5 && ln -sf linxioserver-rpi5 $CHROOTPATH/$USRBINPATH/linxioserver
				;;
			*)
				ln -sf $RPI2LINX $LINXPATH
				chmod 0755 $LINXPATH
				test -x $CHROOTPATH/$USRBINPATH/linxtcpserver-rpi2 && ln -sf linxtcpserver-rpi2 $CHROOTPATH/$USRBINPATH/linxtcpserver
				test -x $CHROOTPATH/$USRBINPATH/linxserialserver-rpi2 && ln -sf linxserialserver-rpi2 $CHROOTPATH/$USRBINPATH/linxserialserver
				test -x $CHROOTPATH/$USRBINPATH/linxioserver-rpi2 && ln -sf linxioserver-rpi2 $CHROOTPATH/$USRBINPATH/linxioserver
				;;
		esac

		# Add Avahi service for LV daemon
		echo $PREAMBLE > $AVAHISVC
		printf "$FMTSTR" "RPi2" >> $AVAHISVC
	fi
fi

if [ -e $CHROOTPATH$BBLINXPATH ]; then
	# BeagleBone Black
	#cat /proc/cpuinfo | grep AM33XX > /dev/null && :
	if [ -e /etc/dogtag ]; then
		# Create symlink to correct liblinxdevice.so
		ln -sf $BBLINX $LINXPATH
		chmod 0755 $LINXPATH
		# Add Avahi service for LV daemon
		echo $PREAMBLE > $AVAHISVC
		printf "$FMTSTR" "BBB" >> $AVAHISVC

		test -x $CHROOTPATH/$USRBINPATH/linxtcpserver-bb && ln -sf linxtcpserver-bb $CHROOTPATH/$USRBINPATH/linxtcpserver
		test -x $CHROOTPATH/$USRBINPATH/linxserialserver-bb && ln -sf linxserialserver-bb $CHROOTPATH/$USRBINPATH/linxserialserver
		test -x $CHROOTPATH/$USRBINPATH/linxioserver-bb && ln -sf linxioserver-bb $CHROOTPATH/$USRBINPATH/linxioserver
	fi
fi

# enable systemd unit files both in the running and offline/container cases
if [ -d /run/systemd/system ]; then
	systemctl daemon-reload
	systemctl enable nisysserver.service
	systemctl start nisysserver.service
	systemctl enable labview.service
	systemctl start labview.service
elif [ -x "/usr/bin/deb-systemd-helper" ]; then
	deb-systemd-helper enable nisysserver.service
	deb-systemd-helper enable labview.service
fi
