#!/bin/sh
# postrm script for lvrt-schroot

systemctl daemon-reload

# remove extra links
CHROOTPATH=/srv/chroot/labview

RESOLVPATH=$CHROOTPATH/etc/resolv.conf
rm -f $RESOLVPATH

UPDATECERTPATH=$CHROOTPATH/usr/bin/update-ca-certificates
rm -f $UPDATECERTPATH

LINXPATH=$CHROOTPATH/usr/lib/liblinxdevice.so
rm -f $LINXPATH

rm -f $CHROOTPATH/usr/bin/linxserialserver
rm -f $CHROOTPATH/usr/bin/linxtcpserver
rm -f $CHROOTPATH/usr/bin/linxioserver

# remove LV avahi service
AVAHISVC=/etc/avahi/services/lvrt.service
rm -f $AVAHISVC
exit 0
