#!/bin/sh
# postrm script for lvrt-schroot

systemctl daemon-reload

CHROOTPATH=/srv/chroot/labview
LINXPATH=$CHROOTPATH/usr/lib/liblinxdevice.so
if [ -e $LINXPATH ]; then
	rm $LINXPATH
fi

AVAHISVC=/etc/avahi/services/lvrt.service
if [ -e $AVAHISVC ]; then
	rm $AVAHISVC
fi
