#!/bin/sh
# postinst script for lvrt-schroot

# make sure we're using systemd
foo=`which systemctl`
if [ $? -ne 0 ]; then
	echo "Systemd must be installed"
	exit 1
fi

# check to make sure the services are installed
# if so, then stop them
foo=`systemctl | grep labview`
if [ $? -eq 0 ]; then
	systemctl is-active --quiet labview.service && systemctl stop labview.service
fi

foo=`systemctl | grep nisysserver`
if [ $? -eq 0 ]; then
	systemctl is-active --quiet nisysserver.service && systemctl stop nisysserver.service
fi

exit 0
