#!/bin/sh
# postinst script for lvrt-schroot

systemctl is-active --quiet labview.service && systemctl stop labview.service
systemctl is-active --quiet nisysserver.service && systemctl stop nisysserver.service

exit 0
